# Spring boot가 제공
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

# Oauth2 관련 속성값 설정
jaenyeong-app:
  admin-email: jaenyeong.dev@gmail.com
  user-email: user@gmail.com
  admin-password: 1234
  user-password: user
  client-id: jaenyeongApp
  client-secret: pass

